[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "http_server"

[dependencies]
tokio = { version = "1", features = ["time", "signal", "rt-multi-thread", "macros", "io-util", "net"] }

